name: Release CLI Binaries

on:
  release:
    types: [published]

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest] # macos-13 for x86_64 support?
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build executable with Versatile PyInstaller
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.12'
          pyinstaller_ver: '==6.11.1'
          requirements: 'app/requirements.txt'
          spec: 'app/main.spec'
          upload_exe_with_name: 'DeepCreamPy-${{ runner.os }}'
          options: --onefile --name "DeepCreamPy" app/main.py

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload Windows binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: artifacts/DeepCreamPy-Windows/DeepCreamPy.exe
          asset_name: DeepCreamPy-x86_64-pc-windows.exe
          asset_content_type: application/octet-stream

      - name: Upload Linux binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: artifacts/DeepCreamPy-Linux/DeepCreamPy
          asset_name: DeepCreamPy-x86_64-unknown-linux
          asset_content_type: application/octet-stream

      - name: Upload macOS binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: artifacts/DeepCreamPy-macOS/DeepCreamPy
          asset_name: DeepCreamPy-aarch64-apple-darwin
          asset_content_type: application/octet-stream